title: Yao An Lee 
logo: "/images/Yao_An_logo.jpg?raw=true" 
description: >  
  Machine Learning Engineer/ Data Scientist
  <br>
  Recent graduate with 2 years of experience creating data pipelines, analyzing data dependencies, reducing data processing run-time, devising research and project-based machine learning model, and boosting model performance
  <br>
  <a href="https://www.linkedin.com/in/yao-an-lee-4848bb1a3/">View My LinkedIn Profile</a> 
  <br>
  <a href="https://github.com/Danielyaoan">View My GitHub Profile</a> 
  
theme: jekyll-theme-minimal

colors:
  crimson: '#900C3F'

