title: Yao An Lee 
logo: "/images/Yao_An_logo.jpg?raw=true" 
description: >  
  Machine Learning Engineer/ Data Scientist
  <br><br>
  Recent graduate with 2 years of experience creating data pipelines, analyzing data dependencies, reducing data processing run-time, devising research and project-based machine learning model, and boosting model performance
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/yao-an-lee-4848bb1a3/">View My LinkedIn Profile</a> 
  <br>
  <b href="https://github.com/Danielyaoan">View My GitHub Profile</b> 
  
# theme                  : "minimal-mistakes-jekyll"
remote_theme           : "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin    : "dirt"

