title: Yao An Lee 
logo: "/images/Yao_An_logo.jpg?raw=true" 
description: >  
  Machine Learning Engineer/ Data Scientist
  
  Recent graduate with 2 years of experience creating data pipelines, analyzing data dependencies, reducing data processing run-time, devising research and project-based machine learning model, and boosting model performance
  
  <a href="https://www.linkedin.com/in/yao-an-lee-4848bb1a3/">View My LinkedIn Profile</a> 
  <a href="https://github.com/Danielyaoan">View My GitHub Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

