title: Yao An Lee 
logo: "/images/Yao_An_logo.jpg?raw=true" 
description: >  
  ML Engineer/ Data Scientist
  <br><br>
  Recent graduate with 2 years of experience in data analysis and model development.
  <br><br>
  <a href="https://www.linkedin.com/in/yao-an-lee-4848bb1a3/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

colors:
  crimson: '#900C3F'

